apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: arc-demo
spec:
  releaseName: hello-arc-prod
  chart:
    git: https://github.com/oaviles/hello_arc.git
    path: charts/hello-arc
    ref: master
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Demo about Azure Arc, Azure Kubernetes Service and GitHub Actions. Powered by OA
